# Generated by Django 3.0.1 on 2020-02-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcareapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('upperBP', models.CharField(max_length=200)),
                ('lowerBP', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
            ],
        ),
    ]
